language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=verbose-ubuntu-min-23.4
    - EMACS_VERSION=verbose-ubuntu-min-24.5
    - EMACS_VERSION=verbose-alpine-min-25.3
    - EMACS_VERSION=verbose-alpine-min-26.1
    - EMACS_VERSION=verbose-alpine-min-26.2

script:
  - make .make/$EMACS_VERSION
